### ISSUE TITLE
rasa installation error

### ISSUE THREAD

**Issue by prince-kumar95** [Limechat/Simple-Hotel-Chatbot#4]
Error message

 ERROR: Command errored out with exit status 1:
     command: 'c:\users\saura\pycharmprojects\untitled1\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saura\\AppData\\Local\\Temp\\pip
-install-hfply9j8\\ujson\\setup.py'"'"'; __file__='"'"'C:\\Users\\saura\\AppData\\Local\\Temp\\pip-install-hfply9j8\\ujson\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__fi
le__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\saura\AppData\Local\Temp\pip-record-z467b0
r9\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\saura\pycharmprojects\untitled1\venv\include\site\python3.6\ujson'
         cwd: C:\Users\saura\AppData\Local\Temp\pip-install-hfply9j8\ujson\
    Complete output (6 lines):
    Warning: 'classifiers' should be a list, got type 'filter'
    running install
    running build
    running build_ext
    building 'ujson' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\saura\pycharmprojects\untitled1\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\
\saura\\AppData\\Local\\Temp\\pip-install-hfply9j8\\ujson\\setup.py'"'"'; __file__='"'"'C:\\Users\\saura\\AppData\\Local\\Temp\\pip-install-hfply9j8\\ujson\\setup.py'"'"';f=getattr(tok
enize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\saura\App
Data\Local\Temp\pip-record-z467b0r9\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\saura\pycharmprojects\untitled1\venv\include\site\pyth
on3.6\ujson' Check the logs for full command output.

**Comment by shubii8992** [comment]
Download Microsoft visual studio community , from here/
https://visualstudio.microsoft.com/

while installing, choose "Build tools for visual studio" workload

**Comment by prince-kumar95** [comment]
Error cleared

**Comment by prince-kumar95** [comment]
Error cleared

**Comment by prince-kumar95** [comment]
I have submitted the assignment. How and when will I graded and informed
about the results.
